### ISSUE TITLE
Feature Request: Read individual .img file

### ISSUE THREAD

**Issue by bogoshipda** [spd789562/wz-reader-rs#2]
Hi there,

If possible could there be a method where only an .img file is read instead of the complete .wz file? Unsure, if that was in your original roadmap but just putting a suggestion out there if you have the bandwidth to put this request in.

Thanks!

**Comment by spd789562** [comment]
I'm actually have a method for that, just not any exmaple yet. But it using like WzFile cuz *.img just a chunk of WzFile.
[src/node.rs#L61](https://github.com/spd789562/wz-reader-rs/blob/main/src/node.rs#L61)

```rust
use wz_reader::{WzNode, WzNodeArc, WzNodeCast};

let node: WzNodeArc = WzNode::from_img_file("some/where/foo.img").into();

// parse wz img
node.write().unwrap().parse(&node);

let node_read = node.read().unwrap();

assert!(node_read.is_parsed);
assert!(node_read.try_as_image().is_ok());
```
