### ISSUE TITLE
Bug: Reading img file gives an error of "invalid utf8"

### ISSUE THREAD

**Issue by bogoshipda** [spd789562/wz-reader-rs#3]
I was testing out your new example file for reading img files and hit a roadblock when testing on my laptop (Macbook Pro M3 chip). When reading the file, Rust panics saying:
```
    Finished release [optimized] target(s) in 0.05s
     Running `target/release/examples/parse_single_img_file`
thread 'main' panicked at src/reader.rs:144:47:
called `Result::unwrap()` on an `Err` value: BadInput { size: 4, msg: "invalid utf8" }
stack backtrace:
   0: _rust_begin_unwind
   1: core::panicking::panic_fmt
   2: core::result::unwrap_failed
   3: wz_reader::wz_image::WzImage::resolve_children
   4: wz_reader::node::WzNode::parse
   5: parse_single_img_file::main
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.
```

I modified the example code a little bit because I wanted to experiment with img to json:
```
let node: WzNodeArc = WzNode::from_img_file("./01002023.img",
     Some(WzMapleVersion::GMS),
      None).unwrap().into();

    let mut node_write = node.write().unwrap();

    node_write.parse(&node).unwrap();
```
I tested with GMS, BMS, EMS, Classic, and None to see if it would make a difference but still same error. The img files are originally from a GMS v83 setup. Here are some img files to test with to see if the problem can be replicated:
https://github.com/bogoshipda/wzoutput/blob/main/00002000.img
https://github.com/bogoshipda/wzoutput/blob/main/GuestEULA.img
https://github.com/bogoshipda/wzoutput/blob/main/MonsterBook.img
https://github.com/bogoshipda/wzoutput/blob/main/Tips.img

Thanks again for your continued work on the wz parser 💯

**Comment by spd789562** [comment]
Thanks for reporting this and provide example file, it been broken cuz i'm mad some change and forget this case.
It should be working now.

And it reminding me, I'm should create test for `img` file make sure it wont be borken.
