### ISSUE TITLE
get_image() returned UnsupportedHeader (21576) error

### ISSUE THREAD

**Issue by creayhx** [spd789562/wz-reader-rs#8]
I am working on a function to export map thumbnails. Some map thumbnails have UnsupportedHeader (21576) errors.
Can you help me check what the reason is?

Example:  [https://github.com/creayhx/wz-parse-dm1.git](https://github.com/creayhx/wz-parse-dm1.git)

**Comment by spd789562** [comment]
there has limitation of WzPng parsing, which only allow four type of WzPng header `0x9C78`, `0xDA78`, `0x0178`, `0x5E78`. but that what MapleLib do, I sould look for it, since im not mat this problem before.

**Comment by spd789562** [comment]
ok... after dig more, those are zip header, and `21576` is not vaild zlib header, even do decryption I can't get right value for it
sorry, can't help you here :/

**Comment by spd789562** [comment]
wait, I'm somehow make it work, maybe release later!

**Comment by spd789562** [comment]
probably resolve on [v0.0.10](https://github.com/spd789562/wz-reader-rs/releases/tag/v0.0.10) release

**Comment by creayhx** [comment]
> probably resolve on [v0.0.10](https://github.com/spd789562/wz-reader-rs/releases/tag/v0.0.10) release

Thank you very much for solving this problem. It has been very helpful to me!
